#!/bin/bash
clear
# -----

MNIP=`wget -qO- http://ipecho.net/plain`;

export GREP_OPTIONS=--color=always

# -----

function wait_clear() {
    PROMPT="
press enter or wait $1 seconds to continue "
    read -p "$PROMPT" -t $1 NOOP;
    clear;
}

# ----------------------------------------------------------------

cat << EOF


   YOU MUST USE DASH-CLI
  FOR THE DASH MASTERNODE
        LIVE STREAM
    TO PROCEED PROPERLY
EOF
echo "-"
echo "-"
echo "----->  PRESS [CTRL-c]"
echo "---->    AT ANY TIME"
echo "--->       TO EXIT"
echo "-->      LIVE STREAM."

# ----------------------------

wait_clear 5;

cat << EOF


***   START DASH MASTERNODE : LIVE STREAM
EOF

# ----------------------------

wait_clear 1;

cat << EOF


***   CHECKING YOUR DASH MASTERNODE IP CONNECTION(S) ON PORT: 9999

`netstat -an | grep 9999 | more`


***   CHECKING YOUR DASH 'LISTENING' ABILITY
***   LISTENING, ON PORT : 9999

`netstat -an | grep LISTEN | grep 9999`
EOF
echo " "
echo " "
date

# ----------------------------

wait_clear 8;

cat << EOF


***GET-INFO FOR 'DASH'

`dash-cli getinfo`
EOF
echo " "
echo " "
date

# ----------------------------

wait_clear 8;

cat << EOF


***YOUR DASH MASTERNODE 'IP' SHOULD = ENABLED

`dash-cli masternode list full | grep $MNIP`
EOF
echo " "
echo " "
date
echo " "
echo " "
echo " "
echo " "
echo " "
cat << EOF
***ZERO IS THE BEST SCORE FOR YOUR MASTERNODE


`dash-cli masternode list full | grep $MNIP`
EOF
echo " "
echo " "
date
echo " "
echo " "
echo " "
echo "..... PRESS [CTRL-c].... AT ANY TIME... TO EXIT.. LIVE STREAM."
# ----------------------------

wait_clear 8;

echo " "
date
echo " "

EOF
# ----------------------------
echo " "
dashR
